version: '3.5'

services:

  #
  # Nginx Container
  #
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./blog:/var/www/html:cached
      - ./nginx/log:/var/log/nginx:cached
      - ./nginx/conf.d:/etc/nginx/conf.d:cached
      - ./certbot/conf:/etc/letsencrypt:cached
      - ./certbot/www:/var/www/certbot:cached
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  #
  # CertBot Container
  #
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt:cached
      - ./certbot/www:/var/www/certbot:cached
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  #
  # PHP-FPM Container
  #
  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ./blog:/var/www/html:cached

  #
  # MySql Container
  #
  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password
      - MYSQL_DATABASE=aegea
    volumes:
      - ./mysql/data:/var/lib/mysql:cached