version: '3.5'

services:

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./blog:/var/www/html
      - ./nginx/log:/var/log/nginx
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ./blog:/var/www/html

  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password
      - MYSQL_DATABASE=aegea
    volumes:
      - ./mysql/data:/var/lib/mysql