version: '3.5'

services:

  #
  # Nginx Container
  #
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./blog:/var/www/html:delegated
      - ./nginx/log:/var/log/nginx:delegated
      - ./nginx/conf.d:/etc/nginx/conf.d:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt:cached
      - ./certbot/www:/var/www/certbot:cached
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  #
  # CertBot Container
  #
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt:cached
      - ./certbot/www:/var/www/certbot:cached
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  #
  # PHP-FPM Container
  #
  php-fpm:    
    build:
      args:
        user: sammy
        uid: 1000
      context: ./php-fpm
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ./blog:/var/www/html:delegated

  #
  # MySql Container
  #
  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password
      - MYSQL_DATABASE=aegea
    volumes:
      - ./mysql/data:/var/lib/mysql:delegated

networks:
  default:
    external: 
      name: br0    